id: AEFE98F36
title: Light Offering Aspiration Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:31:52.261873
  last_modified_at: 2022-03-01 01:31:52.261878
